In [1]:
import re 
import pandas as pd
import os

csv_path = 'train-csv/'
cols_to_keep = ['PLOT_ID', 'SAMPLE_ID', 'LON', 'LAT', 'FLAGGED', 'ANALYSES', 'USER_ID',
       'COLLECTION_TIME', 'ANALYSIS_DURATION', 'TREE', 'plotid', 'sampleid']
csvs = [x for x in sorted(os.listdir(csv_path)) if "v20" in x]
#csvs = [x for x in csvs if "v18" in x]


print(csvs)

dfs = []
for i in csvs:
    df = pd.read_csv(csv_path + i, encoding = "ISO-8859-1")
    df.columns = [re.sub(r'\W+', '', x) for x in df.columns]
    df.rename(columns={'Ã¯plotid':'plotid'}, inplace=True)
    df.columns = [x.upper() for x in df.columns]
    df.columns = ['PLOT_ID' if x == 'PLOTID' else x for x in df.columns]
    df.columns = ['SAMPLE_ID' if x == 'SAMPLEID' else x for x in df.columns]
    df = df.rename(columns={df.columns[0]: 'PLOT_ID'})
    df = df.reset_index()
    df['PLOT_FNAME'] = '0'

    print(f"{str(i[-6:-4]).zfill(2)}")
    
    if len(df) > 0:
        counter = 0
        plot_ids = []
        for index, row in df.iterrows():
            if row['PLOT_ID'] not in plot_ids:
                plot_ids.append(row['PLOT_ID'])
                counter += 1
            df['PLOT_FNAME'][index] = f"{str(i[-6:-4]).zfill(2)}{str(counter).zfill(3)}"
        print("WRITING CSV")
        df.to_csv(csv_path + i, index = False)

['ceo-plantations-train-v20.csv']
20

<ipython-input-1-250f719974b2>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PLOT_FNAME'][index] = f"{str(i[-6:-4]).zfill(2)}{str(counter).zfill(3)}"

WRITING CSV

In [4]:
df.head(5)

,index,PLOT_ID,SAMPLE_ID,LON,LAT,EMAIL,FLAGGED,COLLECTION_TIME,ANALYSIS_DURATION,IMAGERY_TITLE,IMAGERY_ATTRIBUTIONS,SAMPLE_GEOM,PL_COUNTRY,PL_PLANTATION,SYSTEM,PLOT_FNAME
0,0,0,-195,-0.474957,6.038432,jessica.ertel@wri.org,False,2023-05-02 20:16,18.4 secs,Mapbox Satellite,NaN,POINT(-0.474956555934758 6.038432163137827),Ghana,plant,Agroforestry,18001
1,1,0,-194,-0.474957,6.038521,jessica.ertel@wri.org,False,2023-05-02 20:16,18.4 secs,Mapbox Satellite,NaN,POINT(-0.474956555934758 6.038521496234068),Ghana,plant,Agroforestry,18001
2,2,0,-193,-0.474957,6.038611,jessica.ertel@wri.org,False,2023-05-02 20:16,18.4 secs,Mapbox Satellite,NaN,POINT(-0.474956555934758 6.038610829315573),Ghana,plant,Agroforestry,18001
3,3,0,-192,-0.474957,6.038700,jessica.ertel@wri.org,False,2023-05-02 20:16,18.4 secs,Mapbox Satellite,NaN,POINT(-0.474956555934758 6.038700162382341),Ghana,plant,Agroforestry,18001
4,4,0,-191,-0.474957,6.038789,jessica.ertel@wri.org,False,2023-05-02 20:16,18.4 secs,Mapbox Satellite,NaN,POINT(-0.474956555934758 6.038789495434372),Ghana,plant,Agroforestry,18001